### ISSUE TITLE
[XGrid] Column sizes are re-rendered when component state changes

### ISSUE THREAD

**Issue by tarochipz** [mui-org/material-ui-x#1167]
When a state changed is triggered by `onRowClick`, `selectionModelChange` or `onRowHover` re-render occurs that resets the state of a resized column. How should we handle this? Is there a way to persist column sizes if state changes?

Live example: https://www.loom.com/share/a943d5d543464f0cbd72178f4cbe314c
sandbox: https://codesandbox.io/s/infallible-goldstine-qku74?file=/src/App.js

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

See comparison between first and second table in: 
https://codesandbox.io/s/infallible-goldstine-qku74?file=/src/App.js

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by dtassone** [comment]
The problem is that you create a new array of columns at every render. So it reset the columns every time you update the state.

Wrap your columns with `React.useMemo or React.useState` and it will work fine.

**Comment by dtassone** [comment]
https://codesandbox.io/s/friendly-chaplygin-84h1g?file=/src/App.js

**Comment by tarochipz** [comment]
What if a state change impacts rows/columns ? i.e. https://codesandbox.io/s/quiet-frog-imqji?file=/src/App.js

**Comment by LaneRamp** [comment]
i don't think there's a good way of changing this behavior under the hood (could be wrong), but if there were an `onColumnResize` callback or something, perhaps we could hook into that to persist column sizes between state-based re-renderings? just spitballing.

**Comment by oliviertassinari** [comment]
The current column definitions were designed to be definitions, hence to never change during the lifecycle of a component. The only demos in the documentation that don't guarantee a fix reference are the ones that need an inline preview. We could likely document this requirement, it would help.

Regarding customizing the cell based on some external state, currently, you need to use the React context feature. We could consider adding a slot in `componentsProps` to make it easier.

Regarding storing the state of the column width, this problem is interesting and probably related to #190. We currently have a private onStateChange and state that you can leverage as a temporary workaround. 

However, we haven't made it public yet, it's firing very often, the state prop isn't really a controllable prop, you might have surprises.

I wonder if we shouldn't allow developers to subscribe to updates on sub parts of the state as well as truly controlling sub parts.

**Comment by dtassone** [comment]
There is an internal event 'columnsUpdated' that you could subscribe to. But at the moment there is an issue as this one is not firing when column width change. So some refactoring to be done here.

Otherwise you could use apiRef to getAllColumns when the state update. So if `getAllColumns` returns an empty array then you can initialize the grid columns otherwise you can update the columns from the grid columns state.

Check out https://codesandbox.io/s/columnstateupdate-yxgul?file=/src/App.js

Not ideal but it's a workaround while we fix the issue
As a fix we can just add `onColumnsChange` and `onColumnResize`. Would that be ok?

**Comment by tarochipz** [comment]
Thank you both for your help and responses. Having `onColumnsChange` and `onColumnResize` would help resolve our issue. 

I see the `apiRef` prop documented [here](https://material-ui.com/api/x-grid/) but can't find any further documentation on it, is there more examples on usage of this somewhere? I'm wondering if we should just use `apiRef` in general since we're making a lot add-ons and manipulations to the xGrid component.

**Comment by oliviertassinari** [comment]
> Actually docs prob not needed since we can instantiate this to see available methods.

@tarochipz What do you mean? What's your solution? I personally think that we should have an effort in the documentation for better covering our API. What we have more or less work with the API of the components, but it's quickly limited. We could imagine:

- Having a dedicated page for each exported modules. 
- Remove the sub-menu "Components API" and link all the modules inside a single page. 
- Have a custom API rendering block so we can document sub-parts of the modules inside any markdown pages (while keeping the code as the source of truth, no duplication).

This should be relatively easy to do any yet bring a lot of value. We will start to need to benchmark how AWS, Stripe, and other large API/great documentation handle the problem.

**Comment by tarochipz** [comment]
Definitely agree that what you have there will be valuable. What I meant is at the moment we do not need docs since we ended up calling `useGridApiRef()` and looking at the ref object returned to evaluate whether we want to use apiRef.

**Comment by oliviertassinari** [comment]
> Having onColumnsChange and onColumnResize would help resolve our issue.

@tarochipz You can subscribe to #1201.
