### ISSUE TITLE
[DataGrid] Copying a cell (cmd +c) selects and copies the whole row

### ISSUE THREAD

**Issue by Tollwood** [mui-org/material-ui-x#1197]
As a user I want to copy cell content so that I can use it in other places. 
Select + right click copy works fine. Using the keyboard shortcut (cmd/ctrl + c) does select and copy the whole row.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The whole row is selected and copied  instead of just the selection

## Expected Behavior 🤔

only the selection should be copied

## Steps to Reproduce 🕹
Steps:

1. open https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-demos-playground--commodity
2. select / double click a cell
3. use keyboard shortcut (cmd +c / ctrl + c)
4. The whole row gets selected and copied

## Context 🔦

I want to copy cell content from my table and search for this value, use it in another part of the application as an input

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  tested in chrome
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: Not Found
    Firefox: 85.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: 4.0.0-alpha.22 => 4.0.0-alpha.22 
    @material-ui/x-license:  4.0.0-alpha.21 
    @types/react: ^16.9.0 => 16.14.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    typescript: ^3.9.5 => 3.9.9 </details>

## Order id 💳

21977

**Comment by oliviertassinari** [comment]
@Tollwood Thanks for reporting the pain. Does https://material-ui.com/components/data-grid/selection/#disable-selection-on-click solve your issue?

Regarding the next step. I would encourage the following follow-up (yes, there is quite some work 😁):

1. The current row vs. cell copy seems correct:

  - If range selected (via range selection), copy range
  - Else if rows selected (via row selection), copy rows
  - Else copy-focused cell

  However, the API for disabling the row selection with [`disableClickEventBubbling `](https://material-ui.com/components/data-grid/selection/#disable-selection-on-click) might not be right. Maybe we should have something more dedicated.

2. We don't handle selectable cells correctly. For instance, 

  <img width="336" alt="Screenshot 2021-03-13 at 10 06 29" src="https://user-images.githubusercontent.com/3165635/111025347-d0dea880-83e3-11eb-9b5b-7e38f52105bd.png">

  <kbd>cmd</kbd>+<kbd>c</kbd> should respect the current text selection.

3. I think that we should have a section in the documentation just about the copy feature. The page https://material-ui.com/components/data-grid/export/#clipboard seems the best candidate.
4. The current breakdown between MIT, Pro, Premium is probably not correct as a copy is a basic feature. Maybe could have:
- MIT: native text copy
- Pro: cell/row copy, multi-row copy
- Premium cell/row paste, range handling
5. I think that we should update https://material-ui.com/components/data-grid/accessibility/#selection because it's not always true. It's not always copying the row, it can be a cell or a range once we support it.
6. The virtualization is not supported, the whole row isn't copied:

<img width="856" alt="Screenshot 2021-03-13 at 09 59 38" src="https://user-images.githubusercontent.com/3165635/111025206-f0c19c80-83e2-11eb-8fa1-4a21e64cf2b0.png">

I don't think that we should have implemented this feature by manipulating the text selection of the data grid, but using a hidden text, like https://github.com/feross/clipboard-copy/blob/master/index.js.

7. In the future, we might see developers asking for: a. customizing the conversion from cell value to text, b. customizing the delimiter, asking for imperative copy APIs. We can wait

**Comment by Tollwood** [comment]
@oliviertassinari  thanks, for your suggestion.
with [disable-selection-on-click](https://material-ui.com/components/data-grid/selection/#disable-selection-on-click) it works as expected.

**Comment by cmdcolin** [comment]
Just saw this one, but saw disableClickEventBubbling was giving a typescript error. Is the disableClickEventBubbling added to the typescript for the data grid? Thanks :)

**Comment by cmdcolin** [comment]
Sorry I misread for my previous comment, I used disableSelectionOnClick and that worked fine for this :)

**Comment by m4theushw** [comment]
Fixed by #1929

**Comment by oliviertassinari** [comment]
@m4theushw We didn't cover all the points of https://github.com/mui-org/material-ui-x/issues/1197#issuecomment-798040149. I'm moving the discussion to #199.
