### ISSUE TITLE
[DataGrid] GridColumnPanel column search TextField loses focus after typing single character 

### ISSUE THREAD

**Issue by bryyytl** [mui-org/material-ui-x#1254]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Whenever trying to type text into GridColumnPanel column search TextField, I frequently see the GridColumnPanel lose focus after typing a single character.

https://user-images.githubusercontent.com/78176335/111718205-e31b7500-882f-11eb-8ba9-3f13c272e106.mp4

Video example comes from https://material-ui.com/components/data-grid/rendering/#toolbar using Google Chrome. I've also seen the same issue occur within Firefox.

## Expected Behavior 🤔
Column search TextField should not lose focus and user should be able to continue typing without needing to reselect TextField after a single character.

## Steps to Reproduce 🕹
1. Click on "Column" button in GridToolbar
2. Type single character in column search field
3. Observe that the column search field has lost focus

v4.0.0-alpha.12

**Comment by oliviertassinari** [comment]
This is a consequence of #1102 that introduces a trap focus. I have spent ~20 minutes looking into it. We have improved the TrapFocus in v5 which fixes the observation of the issue. However, I would propose two things:

1. We fix the usage of the TrapFocus API with v4. It's a simple one-line change.
2. We improve the implementation of the TrapFocus in the core, the current demos in https://next.material-ui.com/components/trap-focus/ are not right. We risk losing events because we resubscribe too often to the document.

@DanailH Do you want to lead this improvement? It's a simple problem, you can interspace it between two different larger efforts, e.g. perfect when waiting for a review.

**Comment by oliviertassinari** [comment]
For 2. I have open https://github.com/mui-org/material-ui/issues/25528.
