### ISSUE TITLE
[DataGrid] Toolbar component names are inconsistent 

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1256]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

https://github.com/mui-org/material-ui-x/blob/a46e2a13c5f63adc08e44fa2dc1d51e64275e4ac/packages/grid/_modules_/grid/components/toolbar/GridToolbar.tsx#L25-L30

## Expected Behavior 🤔

<img width="412" alt="Screenshot 2021-03-20 at 18 42 55" src="https://user-images.githubusercontent.com/3165635/111880467-1c78ef80-89ac-11eb-97b5-3e429c8bccbb.png">

```jsx
    <GridToolbarContainer>
      <GridToolbarColumns />
      <GridToolbarFilter />
      <GridToolbarDensity />
      <GridToolbarExport />
    </GridToolbarContainer>
```

## Motivation 

Makes it more predictable. For instance, when searching, the density selector is missing:

<img width="401" alt="Screenshot 2021-03-20 at 14 36 32" src="https://user-images.githubusercontent.com/3165635/111871350-b67b7080-8989-11eb-8bbd-3f122cbd95e9.png">

**Comment by DanailH** [comment]
I agree the namings are off. The problem is that their purpose is different. For example, the 2 that are with `button` suffix are just a button really and the content loads in the `PreferencePannel` so it may sound misleading that if someone uses that `GridToolbarColumns ` they would get the full functionality (which won't happen). The other 2 are self-contained featured so that using them will actually five the developer what is expected.
