### ISSUE TITLE
[DataGrid] Forward props in public API

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1369]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The props provided to the public components are swallowed. See the following components:

- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx#L12
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridColumnsToolbarButton.tsx#L9
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx#L17
- https://github.com/mui-org/material-ui-x/blob/25edafedf67bea45f6c6ed15281f3ba8f9b6b65e/packages/grid/_modules_/grid/components/toolbar/GridFilterToolbarButton.tsx#L16
- I didn't find more.

## Expected Behavior 🤔

The props provided to the public components should be forwarded and applied as attributes on the root element. Same for the ref. Can also remove `React.FC` as it's not correct.

## Steps to Reproduce 🕹

- Open https://codesandbox.io/s/material-demo-forked-vyg0z?file=/demo.tsx
- `<GridToolbarExport className="foo" data-testid="export" />` is not working

## Context

This is a follow-up on #1252, #1116

**Comment by DanailH** [comment]
Ok, I think there are probably more then, because when I was doing https://github.com/mui-org/material-ui-x/pull/1252 I applied the fix for all components listed in the `gridSlotComponents.ts` https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/models/gridSlotsComponent.ts

**Comment by DanailH** [comment]
@oliviertassinari how about we apply this fix to only the components we have in the `Toolbar` and `Footer` as we kind of encourage developers to use them to build their own versions of the `Toolbar` and `Footer`. My argument for this is because these are kind of special cases where they are not slot components but are exported. Also if we are to do it for all components we have that would be too much.

**Comment by oliviertassinari** [comment]
I think that it should be done on all the public components per convention exceptions to the rule harm the rule. Now, what you are describing seems to be all the public components that we didn't cover yet so it sounds 👍
