### ISSUE TITLE
[RFC] Remove featureMode in filter and sorting, replace with events propagation

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1378]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Remove feature mode in filtering, sorting would allow to control the events and stop the client side code, to run server code.
This change gives a better control of events and allows more granular changes on the grid.

Editing is built using this approach and it seems to scale better, as it avoids having a server switch on each feature, and it allows to control granular actions.

## Examples 🌈

https://deploy-preview-1287--material-ui-x.netlify.app/components/data-grid/editing/#events

Small play with event propagation...
https://codesandbox.io/s/cocky-snowflake-3cow1?file=/src/App.js

## Motivation 🔦

- Control the event system as native events.
- Catch events and run customise action agnostic of the event trigger
 - Stop default behavior

**Comment by oliviertassinari** [comment]
I have updated the issue into an RFC so we can push the discussion further. This seems important and something we want to bounce ideas around before committing to a specific direction.

@dtassone Could you expand on 1. the current **problem** and 2. the proposed **solution**? For instance, we just got a request, how does it fit?

> My company is considering purchasing your material-ui/x-grid offering.
>
> Do you have any additional details on the server-side features/examples? 
Doesn't have to be fancy - a Github link is totally fine. 
>
> We're looking to replace existing data tables functionality which offers "search as you type functionality". We currently search on the back-end using Elasticsearch which supports simultaneous filtering, multi-column sort, and full-text search. Is this a flow that's possible/supported?

--- 

Going a bit of rail here to try to improve our processes. Considering we work async and aim to implement ideas based on their merit, no matter who comes up with it, it seems that the issue's current description format isn't flying. It doesn't seem to include enough information for other team members and the community to engage in a constructive conversation (for instance, I can't).

In order to solve this problem, one possible solution would be to have all problems, before we work on, to always have an issue with a detailed description providing "enough" information so it can be collaborative. I think that we could have two different issue templates.

A less structured template would be better for the small proposals (e.g of frequency 2/week) while a detailed issue template would be better for the important changes (e.g. of frequency 1/month).

- less structured template: we already ask all members of the community when they want to propose a change in the library to follow: https://github.com/mui-org/material-ui-x/blob/master/.github/ISSUE_TEMPLATE/2.feature.md. Having 1. the problem described 2. the solution proposed seems to be the minimum.
- detailed issue template: It could include: 1. a summary (for people that might not be interested in the details), 2. an example (so we can understand the API implication) 3. the problem (only painful real problems deserved to be solved) 4. the solution 5. the alternatives (pros & cons). React has this template: https://github.com/reactjs/rfcs/blob/master/0000-template.md that seems perfect 👌 

Thoughts?

**Comment by oliviertassinari** [comment]
@dtassone Thanks for the update of the issue's description, it's a step in the right direction.

I don't get how the solution would be superior. As far as I understand it, this would make the server-side mode painful for developers. They would have to know all the events that can trigger a feature, click, keyboard, touch now and update them in the future if we change them. I personally fail to see the value.

Ooooh no, my bad, I withdraw what. I was confused by this RFC proposal's description. Re-reading a third time, I think that what you mean is the following:

```diff
diff --git a/docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx b/docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
index 4fb2f237..db60fe56 100644
--- a/docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
+++ b/docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
@@ -38,7 +38,8 @@ export default function ServerFilterGrid() {
   const [filterValue, setFilterValue] = React.useState<string | undefined>();
   const [loading, setLoading] = React.useState(false);

-  const onFilterChange = React.useCallback((params: GridFilterModelParams) => {
+  const onFilterChange = React.useCallback((event, params: GridFilterModelParams) => {
+    event.stopPropagation();
     setFilterValue(params.filterModel.items[0].value);
   }, []);

@@ -67,7 +68,6 @@ export default function ServerFilterGrid() {
       <DataGrid
         rows={rows}
         columns={columns}
-        filterMode="server"
         onFilterModelChange={onFilterChange}
         loading={loading}
       />
```

The concept is interesting, I think that it could make sense, why not.

However, I strongly think that using event.stopPragation() for implementing it is completely wrong ❌. In #1403 I was supporting why this approach is borderline (and doesn't scale: it doesn't work when we need to rely on native events). But here, we are crossing another line. There are two different notions, 1. what the state of the filtering/sorting 2. how is this state converter into the rows. We should keep them isolated. Your proposal merges 1. and 2.

thought cc @mui-org/x

**Comment by dtassone** [comment]
I'm not sure you completely get what I mean.

> They would have to know all the events that can trigger a feature, click, keyboard, touch now and update them in the future if we change them. I personally fail to see the value.

The goal is to use events such as `cellEnterEdit`, that are triggered by native event such as double click or enter key

**Comment by oliviertassinari** [comment]
@dtassone Ok, there is probably still confusion in the air.

Developers can control the `filterModel` prop from any source. How would they tell if the new prop they provide impacts the rows or not? I don't see how any event handler can solve this problem. We have no guarantee that the filterModel change from an event in the data grid.

**Comment by oliviertassinari** [comment]
Closing the RFC as we have surfaced case that makes the proposal not work
