### ISSUE TITLE
[DataGrid] Cell editing with custom <Select> not working

### ISSUE THREAD

**Issue by khanzzirfan** [mui-org/material-ui-x#1439]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Custom select field is not showing meun item lists. The cell editing is changed to view mode on clicking Select field.

## Expected Behavior 🤔
Expected to show the list of menu items when clicking the Select field in cell edit mode

When cell is in edit mode, the Select field should show the dropdown select menu item options for user to select.

## Steps to Reproduce 🕹
I have created a sandbox here. https://codesandbox.io/s/material-demo-forked-eolox?file=/demo.js

**Comment by dtassone** [comment]
I have managed to fix your issue by stopping the propagation of the cell blur event.

https://codesandbox.io/s/material-demo-forked-0dvim?file=/demo.js

**Comment by dtassone** [comment]
I believe this is a problem with the select component, and it is the same reason why I couldn't use it on the filter panel.

**Comment by oliviertassinari** [comment]
I will have a look, we talk about the select with @eps1lon in https://github.com/mui-org/material-ui/issues/25578

**Comment by m4theushw** [comment]
The problem is not just with Select but any portaled component. When the user opens the select, `event.relatedTarget` will not be within the cell. Maybe we need to bring the logic from ClickAwayListener here.

https://github.com/mui-org/material-ui-x/blob/18cd8e182b74a2cfa5889c7b9fba8d7d5016441d/packages/grid/_modules_/grid/components/cell/GridCell.tsx#L76-L84

**Comment by oliviertassinari** [comment]
@m4theushw Interesting. Let's try to list our options. I could find the following:

1. Implement what I had originally proposed for the exit event: a click on the data grid, not a blur event: #1032 ("Focusing another cell"). It's what Excel, Google Spreadsheet, AG Grid are doing.
2. We fix the positioning issue in the core when `MenuProps={{ disablePortal: true }}` is used on the Select. Encourage developers to do this.
3. Have custom select implementation that dodges the blur. Basically, what can be done is a. move the focus inside the cell. b. stop propagation on the blur from the root of the cell c. open the popup right away programmatically. d. when select onClose is triggered, exit the edit mode.
4. Have developers use a native select, and implement #1320

**Comment by m4theushw** [comment]
@oliviertassinari I could also think in attaching a `focus` event to check if the `event.relatedTarget` of `blur` is inside the tree. If it does, we don't publish the blur event.  https://github.com/mui-org/material-ui-x/issues/1439#issuecomment-824283224 This is similar to what ClickAwayListener is doing to deal with portaled components. Hopefully, it would also work here because we use `blur`, not `mouseup`. 😁

Considering your options, I would go with 1. Although, I suggested above a fix to deal with portaled components, using `blur` is delicate. Anything that pulls the focus (e.g. changing tabs) will make the cell to leave the edit mode. A `click` could work better.

Option 2 could conflict with the `overflow: hidden` of the container. Option 3 requires a custom component and I think we need a solution that solves all future problems we might have. Option 4 could work in the short term (to solve the use case of this issue) but we still need a long term solution.

You mentioned that Excel uses the click, but it depends on the version you're using I think. Excel from Office 365 uses a blur event. If I switch between applications, I leave the edit mode.

![office365](https://user-images.githubusercontent.com/42154031/116950846-ae873f80-ac5c-11eb-9317-b084ed95db66.gif)

**Comment by oliviertassinari** [comment]
I like this option 5 with a focus listener to ignore the blue ones. We do that in the speed dial also I believe. Yeah, option 1 might be great as well.

**Comment by khanzzirfan** [comment]
@dtassone I think I managed to get it  working now by adding event.stop propagation inside on change of the select element. 
Was any fix made recently? 
here is a working example sandbox.
https://codesandbox.io/s/datagrid-selectdropdown-wc4gy?file=/SelectField.jsx

**Comment by Troy96** [comment]
@oliviertassinari On changing the select option, I do not see the selected option inside handleEditRowModelChange function's params.model object. Is this a bug or am I missing something here? Please help.

**Comment by Sakshi-Amoga** [comment]
I used that singleSelect type and added value options too, but I want to customized the menu items, how can I do that?

**Comment by SakshiGupta19** [comment]
I used that singleSelect type and added value options too, but I want to customized the menu items, how can I do that? @oliviertassinari
