### ISSUE TITLE
[DataGrid] The `backspace` key empties no editable cells

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1452]
When I select a cell by click on it and then I press the Backspace button from the keyword the cell completely clears.

I'm already using disableSelectionOnClick and disableClickEventBubbling.

**THE SAME ISSUE IS WITH DELETE BUTTON ALSO.**

![download](https://user-images.githubusercontent.com/3165635/115548394-b7186700-a2a7-11eb-8ce0-5e7d62deb172.png)

SandBox Link: https://codesandbox.io/s/datagrid-quick-start-forked-446ly

**Comment by oliviertassinari** [comment]
Related to #1300

**Comment by dtassone** [comment]
Why is it related to #1300? #1300 is fixed in v4.0.0.alpha-25

According to the spec #1032 

### Start editing

The different ways to trigger the edition. I think that we need to document them:

- Edit key:
  - <kbd>Enter</kbd>: focus the field at the end.
  - <kbd>Delete</kbd>: empty the field (do not focus it)
  - <kbd>Backspace</kbd>: empty the field (do not focus it)
- Printable key: focus the field, empty the field and start typing the letter into it
- Double click
- Imperative API call: `toggleCellMode(mode: 'edit' | 'view')`,

**Comment by oliviertassinari** [comment]
> #1300 is fixed in v4.0.0.alpha-25

@dtassone Not really, 1 of the 6 issues reported has been fixed.

> According to the spec #1032

Please have a closer look at the reproductions. The cells are not editable.
