### ISSUE TITLE
[DataGrid] Clicking on the filter icon in header title is not opening the filter panel

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1618]
- open https://material-ui.com/components/data-grid/#mit-version
- add a fitler on a column 
- click on the filter icon of the filtered column
- The filter panel should open

**Comment by oliviertassinari** [comment]
@dtassone If you could add the DataGrid component label, it would be great, it helps differentiate between MIT and commercial impacts, and once we work on more than a DataGrid, to differentiate the efforts.

**Comment by m4theushw** [comment]
That's a regression from #1421. Because of the added `React.memo`, the `GridColumnHeaderItem` is only rendering when there's a prop changes. Since a click in the filter icon doesn't cause a prop change but a change in the state, it doesn't know when to show the preferences panel.  #1415 is also broke after pulling changes from master. 

Can we remove `React.memo`? It was added in https://github.com/mui-org/material-ui-x/pull/1421/commits/09c285bd3e2f0cd2b10f17c319aa9653174f9d5f. Does it fix the tab roving bug or is it for performance reasons?

https://github.com/mui-org/material-ui-x/blob/af5c05f572f787ed01c32241da78b805d94badfd/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L45-L48

**Comment by m4theushw** [comment]
Calling `getState` only gets the updated state in the handlers. All `useGridSelector` (like below) will use the old value. I think that passing state values as props is a solution. We'll have to move a bunch of them to `GridColumnHeadersItemCollection`.

https://github.com/mui-org/material-ui-x/blob/af5c05f572f787ed01c32241da78b805d94badfd/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L58-L60

**Comment by oliviertassinari** [comment]
As a general note, we have faced the same problem in the past: https://github.com/mui-org/material-ui-x/pull/666.

**Comment by dtassone** [comment]
> > when the component is memoized which is normal I believe
> 
> @dtassone Could you expand on what you mean by normal? I can interpret it in two different ways:
> 
> 1. it's how React and the context works
> 2. it's an implementation tradeoff
> 
> Did you mean one of these two?

If the component is memoized then, React will do a shallow comparison of the props to know if it will update.
So if the props don't change then it won't rerun the component function.
This is the reason why, I was memoizing only the last component of the tree, ie the cells, but now we improved that a bit.

Check this example
https://codesandbox.io/s/rendermemocomponent-ig560
You 2 memo components, 1 with a prop and the other without, you will see that the one without prop won't log when the parent state change

**Comment by oliviertassinari** [comment]
@dtassone Ok, I think that we all agree on how React handles memorization, I had also assumed we already agreed on this.
My question was on the next layer. We could be using the context to bypass the memorization of React. Did we not leverage it as an implementation tradeoff (2.) (e.g. no need/doesn't help with performance, no time for it), or because we didn't consider the option at all (1.)?

**Comment by oliviertassinari** [comment]
@dtassone bump
