### ISSUE TITLE
[DataGrid] Setting page with ApiRef in useEffect does not work anymore

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1815]
Broken story
https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-pagination--page-2-api

Expected to render rows 51-100 of 2000

Instead it renders rows 1-50 of 2000

TODO add as snap test

**Comment by oliviertassinari** [comment]
@dtassone When you open an issue, please always follow the issue template. For instance, we miss a codesandbox and the version.

**Comment by oliviertassinari** [comment]
Regarding the change of behavior, it originates from #1583 (not from the refactoring part, from the fix of #1517). As a side note. I should have moved the refactoring to a different PR, this is a great example of what I did [sucks](https://github.com/mui-org/material-ui-x/pull/1583#issuecomment-834750710).

**Comment by flaviendelangle** [comment]
The `useEffect` in the story component occurs just after the `useEffect` in `useData` is triggered.
So the story component has not yet rerendered with the data.

If I add a check on the rows length in the `useEffect` in the story component, the `setPage` occurs after the story component has rerenderer with the data

```ts
  React.useEffect(() => {
    if (data.rows.length) {
      apiRef.current.setPage(1);
    }
  }, [data, apiRef]);
```

But, it's still to soon because it occurs before the `useEffect` in `useGridPagination` has updated the `pagination` state with `rowCount` > 0.

For me the real issue here is that we have async cascade state update, so the `useEffect` in the story component can be called with an intermediate state.

We should trigger the `setGridState` currently in the [useEffect in useGridPagination](https://github.com/mui-org/material-ui-x/blob/1210f1a7cbefff1ad30e6f326db6925975c33c80/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L94) synchronously whenever the `visibleRowCount` changes, not in a `useEffect`.

**Comment by flaviendelangle** [comment]
Relates to #2044 (check after refactoring the pagination with the new controlled state pattern)

**Comment by flaviendelangle** [comment]
I confirm that #2099 fixes this one
