### ISSUE TITLE
[DataGrid] Gap after the last column when all the column widths are set to fluid

### ISSUE THREAD

**Issue by ps-nchang** [mui-org/material-ui-x#2011]
A slight gap is shown between the last column and DataGrid's border when all the column's widths are set to fluid with `flex` attribute and with the following three options turned on for the DataGrid
`showCellRightBorder`, `showColumnRightBorder`, and `disableExtendRowFullWidth`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When all the column's widths are set to fluid with `flex` attribute, each column width must have been calculated but there is a slight gap between the last column and the border. This behavior might have something to do with `disableExtendRowFullWidth` option is being turned on.  The is not an issue if the column widths are set with explicit pixel sizes. 
The same behavior occurs in X-Grid widget, too.

## Expected Behavior 🤔
There should be no gap between the last column and the border even when all the column's widths are set to fluid with `flex` attribute and even if `showCellRightBorder`, `showColumnRightBorder`, and `disableExtendRowFullWidth` options are set.

## Steps to Reproduce 🕹

Please see this https://codesandbox.io/s/material-demo-forked-qrcgo?file=/demo.js to show the issue. Pay attention to the last column's gap and the border.

<img width="417" alt="Capture d’écran 2021-07-24 à 23 43 12" src="https://user-images.githubusercontent.com/3165635/126881646-46e8a8d9-7295-4a3c-a2dd-fa2b08e5e1f3.png">

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
npx: installed 2 in 3.408s

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: ^5.0.0-alpha.33 => 5.0.0-alpha.33 
    @material-ui/data-grid: ^4.0.0-alpha.30 => 4.0.0-alpha.30 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^5.0.0-alpha.33 => 5.0.0-alpha.33 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @material-ui/private-theming:  5.0.0-alpha.33 
    @material-ui/styled-engine:  5.0.0-alpha.26 
    @material-ui/styles:  5.0.0-alpha.33 
    @material-ui/system:  5.0.0-alpha.33 
    @material-ui/types:  6.0.0 
    @material-ui/unstyled:  5.0.0-alpha.33 
    @material-ui/utils:  5.0.0-alpha.33 
    @material-ui/x-grid: ^4.0.0-alpha.30 => 4.0.0-alpha.30 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.30 => 4.0.0-alpha.30 
    @material-ui/x-license:  4.0.0-alpha.30 
    @types/react:  17.0.5 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by m4theushw** [comment]
In this example, the size of the viewport is 398px. Calculating 398px / 3 columns gives ~132.6px. Since we round to floor this value the sum of all 3 columns takes 396px, that's why the small gap after the last column. The first part of the fix would be to remove the rounding in:

https://github.com/mui-org/material-ui-x/blob/f212980940b6b2d2ca56f6c479b43a30af558cad/packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts#L64

Then we need to deal with the double border at the last column. Without diving into the implementation, we need to check if the space left after the last column is zero and if it does then don't apply the border.

![79BSCpnW5r](https://user-images.githubusercontent.com/42154031/124315740-ca1ea180-db4a-11eb-96a2-16df70907771.png)

**Comment by oliviertassinari** [comment]
> The first part of the fix would be to remove the rounding in:

I would be careful with removing the rounding, as Flavien raised it in https://github.com/mui-org/material-ui-x/pull/2104#issuecomment-876957880. Why? Because we rely on the column width to implement virtualization. It might lead to more issues in the future. Now, because it doesn't cost us much to fix it this way 👍 for:

1. removing the floor
2. using the snap and functional test of #2110
3. waiting for seeing the limit of this quick-win
