### ISSUE TITLE
Why my actions github have just to broken, is because of materialui?

### ISSUE THREAD

**Issue by harryp-art** [mui-org/material-ui-x#2096]
A few moments ago the deploy with the actions worked fine, but when I joined the last pr the actions it broke, and I think it is because of materialui, but I did not install any library recently.

this is i am getting:

```diff
-className="MuiGrid-root makeStyles-priceRow-3 MuiGrid-container MuiGrid-item MuiGrid-justify-xs-center MuiGrid-grid-xs-4 MuiGrid-grid-sm-2"
+className="MuiGrid-root makeStyles-priceRow-3 MuiGrid-container MuiGrid-item MuiGrid-justify-content-xs-center MuiGrid-grid-xs-4 MuiGrid-grid-sm-2"
```

## Context 🔦
i am getting this error

> Material-UI: The fade color utility was renamed to alpha to better describe its functionality.
You should use `import { alpha } from '@material-ui/core/styles'`

## Your Environment 🌎

t but I'm not using fade, I don't know why I'm getting this error if I'm not using fade

this is my dependencies:

```
"dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/styles": "^4.10.0",
    "gatsby-plugin-material-ui": "^2.1.10",
    "material-ui-dropzone": "^3.3.0",
```

**Comment by harryp-art** [comment]
@oliviertassinari can you help me please

**Comment by oliviertassinari** [comment]
👋 Thanks for using Material-UI! We use GitHub issues exclusively as a bug and feature requests tracker, however,
this issue appears to be a support request. For support, please check out https://material-ui.com/getting-started/support/. Thanks! If you have a question on StackOverflow, you are welcome to link to it here, it might help others. If your issue is subsequently confirmed as a bug,  and the report follows the issue template, it can be reopened.
