### ISSUE TITLE
[DataGrid] Missing selection controllable API

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#246]
Based on #190

### Benchmark

- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/

**Comment by BrentFarese** [comment]
Is it currently not possible to control selection state on `XGrid` using the `apiRef` (e.g., `apiRef.current.selectRows`)?  Is this ticket limited to exposing a "public" API for controlling the selection state of rows?  Asking since we are considering a use case where we need to control the selection of rows and was contemplating using the `apiRef` to do so while this is pending.  Thanks!

**Comment by dtassone** [comment]
Hi Brent, yes it's possible to control the selected rows using the apiRef, have a look at our storybook 
https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-selection--api-pre-selected-rows
Check the story tab to see the source
Yes this issue is limited to exposing an API prop to control do that

**Comment by BrentFarese** [comment]
> Hi Brent, yes it's possible to control the selected rows using the apiRef, have a look at our storybook
> https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-selection--api-pre-selected-rows
> Check the story tab to see the source
> Yes this issue is limited to exposing an API prop to do that

@dtassone thank you!  We will give this a shot before the prop is implemented.

**Comment by edonadei** [comment]
Hi, any news about that feature to be available on the Datagrid ? I tried the apiref solution, but it looks like it's limited to enterprise only so I just can't use it.

**Comment by oliviertassinari** [comment]
@edonadei We have started to work on a state prop to allow doing such #533. I'm not sure when it will land. Upvotes on this issue will help us prioritize.

**Comment by SvenFaerber** [comment]
I would also vote to have the selected IDs handed over as an array of IDs in a prop, just like they are returned by the onSelectionChange event.

When using it in a stepper with the option to switch back and forth, you need an easy way to reproduce the former selection, when switching back and forth between steps. Handing over the stored array from the corresponding step would be very consistent behaviour.

**Comment by qkdreyer** [comment]
Coming from https://material-ui.com/components/data-grid/selection/#apiref (and https://codesandbox.io/s/dgq0y), I'm wondering if it is possible to control the selection without `apiRef` for the `DataGrid` component (not `XGrid`)

**Comment by oliviertassinari** [comment]
@qkdreyer We don't encourage the usage of the `apiRef` as the default pattern. It breaks the declarative API paradigm of React. It's meant for cases where the declarative approach isn't good enough, so far, you will find streaming.
