### ISSUE TITLE
[DataGrid] The `hideFooterRowCount` prop should only be available for DataGridPro

### ISSUE THREAD

**Issue by alb7h** [mui-org/material-ui-x#2509]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current Behavior 😯

Does not hide the row count

### Expected Behavior 🤔

Should hide the row count

### Steps to Reproduce 🕹

Add `hideFooterRowCount` to the props, and see it doesn't hide.

or click here - https://codesandbox.io/s/compassionate-murdock-sv1me?file=/src/Demo.tsx

Just FYI I'm using the pro datagrid, but the reproduction above is copied from a demo that uses the MIT version, which still presents the issue.

### Context 🔦

I'm building against an endpoint that won't expose exactly how much data it has, and along with that I'm doing cursor based paging. 

So my intention is to set the rowCount to the largest number possible, and then when there is less than the page size returned in data, set the rowCount to currentPage * pageSize + rows.length, which should currently disable the next page button. Ideally I would just like to access the underlying implementation (I.E `onNextPage` `onPreviousPage` `disableNextPage` `disablePreviousPage`) but alas I work with what I have for now.

### Order id 💳

28357

**Comment by m4theushw** [comment]
The `hideFooterRowCount` only works with the pagination disabled. It hides the "Total Rows" label. 

<img width="250" src="https://user-images.githubusercontent.com/42154031/131536512-d8410159-42e5-488b-bb7e-194d734694e9.png" alt="image" style="max-width:100%;">

> I'm building against an endpoint that won't expose exactly how much data it has, and along with that I'm doing cursor based paging.

Since you don't know _a priori_ how many rows you have, our cursor pagination [demo](https://material-ui.com/components/data-grid/pagination/#cursor-based-pagination) is not enough. To hide the "1 - 10 of 100" label you can [override](https://material-ui.com/components/data-grid/components/#pagination) the default pagination component. This slot, by default, uses the [TablePagination](https://material-ui.com/api/table-pagination) component. If you like, you can pass `count={-1}` to it and it won't mention the row count, but an approximation. 

---

We should remove `hideFooterRowCount` from the DataGrid because it only works with the pagination disabled, which is always enabled by default. I labelled this issue with "good first issue" so the community can fix that.

```diff
diff --git a/packages/grid/data-grid/src/DataGridProps.ts b/packages/grid/data-grid/src/DataGridProps.ts
index ad60d800..fa2fb9e8 100644
--- a/packages/grid/data-grid/src/DataGridProps.ts
+++ b/packages/grid/data-grid/src/DataGridProps.ts
@@ -20,6 +20,7 @@ export type DataGridProps = Omit<
   | 'pagination'
   | 'scrollEndThreshold'
   | 'signature'
+  | 'hideFooterRowCount'
 > & {
   pagination?: true;
 };
```

**Comment by alb7h** [comment]
Sorry for the delay in replying. For now I've decided to update the container I was using to wrap the grid to hide it via css. 

```ts
export const GridContainer = styled(Paper)({
  flexGrow: 1,
  '.MuiDataGrid-root': {
    border: 'none',
  },
  '.MuiTablePagination-displayedRows': {
    display: 'none',
  },
});
```

I do want to ask though, can this prop also be extended to cover the paginated row count / page tracker?

**Comment by MichalReifer** [comment]
you can customise the label with this attribute:
```
<DataGrid
  {...data}
  localeText={{
    MuiTablePagination: {
      labelDisplayedRows: ({ from, to, count }) =>
        `${from} - ${to} of ${count === -1 ? `more than ${to}` : count}`,
    },
  }}
/>

```
see at:
[https://mui.com/x/react-data-grid/localization/#translation-keys](url)
