### ISSUE TITLE
Button style is changed when using data-grid

### ISSUE THREAD

**Issue by sheshanth** [mui-org/material-ui-x#2665]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/24425933/134166282-ef5b3e0d-ca33-47bc-ad53-da12abce4ebd.png)

Importing Button from '@mui/material' does not render the default material button.

### Expected behavior 🤔

![image](https://user-images.githubusercontent.com/24425933/134166100-92ed9a15-9e71-4f86-9030-bbad1f9685d0.png)

The button appears normal when importing from '@material-ui/core'

### Steps to reproduce 🕹

Steps:

1. use data grid and material button in same component.
2. import { Button } from '@mui/material' 
3. import { DataGrid } from '@mui/x-data-grid'
4. The style of the button changes from what it has to look like.

I've attached a codesandbox link where I've reproduced the issue: [link to reproduce issue](https://codesandbox.io/s/frosty-sunset-ol08k?file=/src/App.js)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by ZeeshanTamboli** [comment]
I think there are multiple instances of Button styles getting applied in the codesandbox due to both MUI v5 and @material-ui/core v4 packages installed. To support only MUI v5 with the DataGrid, you have to upgrade `@mui/x-data-grid` and `@mui/x-data-grid-generator` to latest `5.0.0-beta-1` by doing `npm install @mui/x-data-grid@next`. It will be mentioned in the docs in #2663 .

See this codesandbox with the the correct button contained style: https://codesandbox.io/s/nameless-dream-r0htn?file=/src/App.js
