### ISSUE TITLE
Re-add row to valueFormatter

### ISSUE THREAD

**Issue by TriPSs** [mui-org/material-ui-x#2684]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In #2581 the params in `valueFormatter` where changed and the `row` value has been removed, is it possible to add this value back or a way to retrieve it through the api?

### Motivation 🔦

We have custom `columnTypes` that render amounts with their correct currency, the currency is configured in a other field of the row and therefore we need to full row data to render the amount in the correct currency.

**Comment by TriPSs** [comment]
Ticket can be close, solved it by correctly formatting the values needed in `valueGetter`

**Comment by m4theushw** [comment]
I'm reopening because we should pass at least the `id` of the row. With the field and ID, the API can be used to get the rest of the information.

https://github.com/mui-org/material-ui-x/blob/609248ea030cf6ca657bfae92f23bea3ba868c2b/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts#L118-L122
