### ISSUE TITLE
Using Autocomplete in a Cell[question] 

### ISSUE THREAD

**Issue by vsspt** [mui-org/material-ui-x#2743]
### Order ID 💳

#28950

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Using Autocomplete in a Cell does not retain the new value after changing it.

### The problem in depth 🔍

Not sure if this is a bug, and although i've checked the documentation, something might be missing from my side.

Basically, i have a Cell that onEdit, renders an Autocomplete control.
BUT, after editing the value, the Cell, does not retain the input value, and reverts to the default cell value.

I've created an Codesandbox demo here: https://codesandbox.io/s/intelligent-meninsky-1vpqc?file=/src/App.js:0-1188

Please note: The Sandbox is using @mui/x-data-grid-pro, version 4.0.0, but i'm using the latest 5.0.0-beta.2.

To reproduce the behavior, please do:
1. Goto the provided sandbox,
2. Double Click on one row to open the Edit Mode, change the select value
3. Note how after the value is changed, the Cell reverts to the default value

### Context 🔦

We need to be able to have a cell that renders an Autocomplete control.

### Your environment 🌎

System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: Not Found
Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)

**Comment by m4theushw** [comment]
You need to call `api.setEditCellValue` to store the new value selected. In the docs, there's [this](https://mui.com/components/data-grid/editing/#custom-edit-component) section showing an example of a custom edit component.

Since you want to use the Autocomplete, you can take as inspiration the code from the "Unit Price Currency" column of the main demo:

<img width="300" src="https://user-images.githubusercontent.com/42154031/135367129-4ae8c31e-6b67-43c8-b6a2-8b18374e70ed.png" alt="image" style="max-width: 100%;">

https://github.com/mui-org/material-ui-x/blob/71cc0d3e6471cd6068a8fba555620953c553a377/packages/grid/x-grid-data-generator/src/renderer/renderEditCurrency.tsx#L47-L53

**Comment by vsspt** [comment]
Thank you, it worked perfectly!
