### ISSUE TITLE
[DataGrid] Tooltip for Action Icon

### ISSUE THREAD

**Issue by Pavel-Ilmenkov** [mui-org/material-ui-x#2871]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Action icon may show the tooltip with text optionally provided by GridActionsCellItem.tooltip (?) property 

### Motivation 🔦

The icon itself may have not enough meaning about the action it performs, so sometimes the textual description will allow to avoid wrong user activities.

### Order ID 💳 (optional)

#30246

**Comment by alexfauquette** [comment]
What do you think about wrapping the Icon into a ToolTip, to provide this information? I put here an example

https://codesandbox.io/s/columntypesgrid-material-demo-forked-7ihvr?file=/demo.tsx

**Comment by md250721** [comment]
@alexfauquette - the tooltip seems to not work if the Action cell is disabled. Please see this forked codesandbox with the delete button disabled: https://codesandbox.io/s/columntypesgrid-material-demo-forked-59suib?file=/demo.tsx

Is there any way around this?

**Comment by alexfauquette** [comment]
That's not related to the Data Grid. The issue is to use Tooltip with a disabled button

https://stackoverflow.com/questions/61115913/is-it-possible-to-render-a-tooltip-on-a-disabled-mui-button-within-a-buttongroup

If you want to had haky customization, you might need to create your custom `ActionCellItem`. It's basically, a helper to switch between `IconButton` and `MenuItem`. You can find the source code here:

https://github.com/mui/mui-x/blob/2d912d78228f57842b911b045d54980e3e4eb1ef/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx
