### ISSUE TITLE
[DataGrid] Add documentation on how to persist edited cells/rows

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#3101]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The nominal use case of the data grid edit feature is to modify the data and then to **persists** the changes in a DB. And, yet, none of the demos in https://mui.com/components/data-grid/editing/ clearly describes how to do this. This seems to be a major opportunity.

### Examples 🌈

@m4theushw Put a demo together: https://codesandbox.io/s/basiceditinggrid-material-demo-forked-m140n?file=/demo.tsx

### Motivation 🔦

This started from the email Tyler McKee from United Airlines sent us:

> A large use case we have is the need to update a row or cell and have it send a request to the backend. While playing around with this I am having trouble figuring out a way to do this that doesn't seem overly complicated. Is there a demonstration of this or just simply updating state somewhere in the docs? I can't justify this purchase without that capability.

I couldn't help myself to think that the large majority of the developers of the people will face the same pain. For the next steps, here is one proposal:

- [ ] 1. We add a "### Server-side persistence" just before https://mui.com/components/data-grid/editing/#start-editing
- [ ] 2. We add a "### Server-side persistence" just before https://mui.com/components/data-grid/editing/#start-editing-2.

---

And to seriously consider:

- [ ] 3. We change the API of `onRowEditCommit(id :string, …)`. Is only returning the id of the row good enough? It forces the MIT users to upgrade to the pro plan, this is not what we advertise: we say that row edit is MIT, but it's not really. I believe the API of `onCellEditCommit(params: GridCellEditCommitParams, …)` is a lot better in this regard. Developers can persist the new cell's value without any apiRef call. Now, we also have [a discussion](https://www.notion.so/mui-org/Free-version-Pro-version-scopes-c81b2e6fee4d404880fad5bd25836739#2ea50470c6b041e7a2f8ed4827b6f54a) about moving some of the apiRef's methods to the public space, so maybe this will solve the problem.
- [ ] 4. We consider the use case of a new `editMode:? "server" | "client"`. Currently, the changes are optimistically shown as persisted in the database. But what if a developer wants to opt out of the optimistic update? Then I believe an edit more, as we do with [`paginationMode`](https://mui.com/components/data-grid/pagination/#server-side-pagination), `sortingMode`, etc. would help.
- [ ] 5. We rename the current `editMode` prop to something else, it could be confusing for developers that are using `paginationMode`, `sortingMode`, etc.

**Comment by flaviendelangle** [comment]
>  3. We change the API of onRowEditCommit(id :string, …). Is only returning the id of the row good enough? It forces the MIT users to upgrade to the pro plan, this is not what we advertise: we say that row edit is MIT, but it's not really. I believe the API of onCellEditCommit(params: GridCellEditCommitParams, …) is a lot better in this regard. Developers can persist the new cell's value without any apiRef call. Now, we also have a discussion about moving some of the apiRef's methods to the public space, so maybe this will solve the problem.

This is a perfect example of why I think the `apiRef` should be public, and not just a few methods.
We should probably pass params to `onRowEditCommit` like for `onCellEditCommit`.
But on the free version, you will still not be able to revert the changes in case the server refuses the update, because you don't have access to `apiRef.current.updateRows`.
These limitations feels arbitrary to be and not representative of basic / advanced use cases.

Meanwhile, I marked the new docs paragraph as pro-only.

**Comment by m4theushw** [comment]
> 3. We change the API of onRowEditCommit(id :string, …). Is only returning the id of the row good enough? It forces the MIT users to upgrade to the pro plan, this is not what we advertise: we say that row edit is MIT, but it's not really. I believe the API of onCellEditCommit(params: GridCellEditCommitParams, …) is a lot better in this regard.

@oliviertassinari Only adding the new row to `onRowEditCommit` will not solve the problem. The handler of `rowEditCommit` also contains the logic for the value setter. This way, if users override this event and prevent the default behavior, they loose the ability of save values into nested structures.

https://github.com/mui-org/material-ui-x/blob/becd7f07faf00cef946ce45436bd92920d68dba1/packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts#L385

> 4. We consider the use case of a new editMode:? "server" | "client". Currently, the changes are optimistically shown as persisted in the database. But what if a developer wants to opt out of the optimistic update? 

Why not remove the optimistic mode? For enterprise applications, giving the impression that it was saved when it wasn't yet may cause more harm than good.

> 5. We rename the current editMode prop to something else, it could be confusing for developers that are using paginationMode, sortingMode, etc.

I don't know. There's only step in the cell/row editing that changes depending if it's server or client: the commit process. The other tasks (e.g. start, stop, validation) is the same.

> Meanwhile, I marked the new docs paragraph as pro-only.

@flaviendelangle For MIT users, the `editRowsModel` can be used. It has limitations but it works if `singleSelect` is not used.

---

My proposal:

1. Remove `editRowsModel` in v6 because it's only useful for doing validation. However, it breaks the `singleSelect` and it's not intuitive for users: #2727.
2. Remove the optimistic commit and create the `processRowCommit` and `processCellCommit` (better names are welcome) props fired immediately before https://github.com/mui-org/material-ui-x/blob/becd7f07faf00cef946ce45436bd92920d68dba1/packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts#L390

    These two new props will have to return a promise. If the promise resolves, we update the row and leave the edit mode. If it's rejected stay in the edit mode. The new props will receive the old and new row after passing through the value setters. 
3. Pass a `saving` prop to each edit cell so the input can be disabled during the save.
4. Fix to not fire in parallel the following events. It should only leave the edit mode if the commit was successful.  https://github.com/mui-org/material-ui-x/blob/becd7f07faf00cef946ce45436bd92920d68dba1/packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts#L96-L97
