### ISSUE TITLE
[DataGrid] Editing behavior is broken with composite cells

### ISSUE THREAD

**Issue by Edelf** [mui-org/material-ui-x#3150]
### Order ID 💳

#28950

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Not sure if this is a bug or something is wrong with my code:
https://codesandbox.io/s/valuegettersettergrid-material-demo-forked-24tei?file=/demo.tsx

With a grid in editMode="row", changing the value of the cell CUSTOMERGROUP or DEPARTMENT and moving the focus to another cell, causes the first cell to revert to it's original value.

Steps:
1.  Double click on the first row to go into Edit Mode
2.  Change value of CUSTOMERGROUP from LARGE to SMALL
3. Without exiting the the Edit Mode, select another cell on the first row
4. The value of CUSTOMERGROUP  was reverted to LARGE

The same problem does not occur with the "Full Name" column.

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Thank you for your feedback.
The issue here is that we save every cell one after another.  
So if you change the "Last name" to be "Stark", it will do the following:

1. Set "First name" to "Jon" (col: "First name")
2. Set "Last name" to "Stark" (col: "Last name")
3. Set "First name" to "Jon" and last name to "Snow" (col: "Full name")
4. ... continue for other columns

This makes `valueSetter` unusable in this kind of scenario.

You can manually synchronize the two cells by listening to the `editCellPropsChange` 
I modified your example with a basic implementation [here](https://codesandbox.io/s/valuegettersettergrid-material-demo-forked-ff0ni), there are probably edge cases missing.

But I think we should improve our behavior in the future.
A first improvement would be for instance to not apply the value of cells which have not been modified (<=> add a `dirty` status to each cell).
Not sure if we should go further and do the synchronization ourselves.

**Comment by Edelf** [comment]
@flaviendelangle could you please double check if the link is correct? The code is same as mine and it has a missing dependency

**Comment by flaviendelangle** [comment]
:sob:  I lost my work
Well, I'm good for a 2nd round

**Comment by Edelf** [comment]
Keep in mind that what I was describing occurs without leaving the edit mode.
While in edit mode, moving to another cell reverts the initial cell to it's original value

**Comment by flaviendelangle** [comment]
@Edelf  https://codesandbox.io/s/valuegettersettergrid-material-demo-forked-ff0ni? here it is
For me it also work when going from cell to cell without leaving edit mode.

**Comment by Edelf** [comment]
@flaviendelangle I think we are talking about different things.
The problem is the following:
1. Double click on the first row to go into Edit Mode
2. Change value of CUSTOMERGROUP from LARGE to SMALL
3. Without exiting the the Edit Mode, select another cell on the first row
4. The value of CUSTOMERGROUP was reverted to LARGE
![f09WFwWqwn](https://user-images.githubusercontent.com/9094216/141130221-4915c305-3d62-4392-a8c1-9de99b539931.gif)

**Comment by m4theushw** [comment]
You're always passing the the value of the row to the Autocomplete. You need to pass the value that the user has selected. The following change should fix your example.

```diff
-const newValue = params
-  .getValue(params.id, element.code)
-  ?.toString();
+const newValue = params.value;
```

In https://mui.com/components/data-grid/demo/, one of the fields uses the Autocomplete. You can check its source code to see how it was wired:

https://github.com/mui-org/material-ui-x/blob/56610e553ef32afab69ac169c78674430aa2a4ce/packages/grid/x-data-grid-generator/src/renderer/renderEditCountry.tsx#L59

**Comment by Edelf** [comment]
Thank you @m4theushw that solved the problem!
