### ISSUE TITLE
[DataGrid] Override default selected `row` styling

### ISSUE THREAD

**Issue by VladParshin** [mui-org/material-ui-x#3311]
### Order ID 💳

29879

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Attempting to override the background color on a selected Row, through a theme via createTheme and ThemeProvider

### The problem in depth 🔍

I'm having an issue getting the context right to override a style in my black and white theme for the datagrid Pro.
The expected behavior is that the snippet below, will make selected row have a black background. And at the same time, change the text to be white. I haven't applied the text part yet.
```
   overrides: {
        MuiDataGrid: {
            root: {
                backgroundColor: "#fff",
                row: {
                    "&$selected": {
                        backgroundColor: "#000",
                    },
                },
            },

        },
    },
```

### Context 🔦

In a black and white theme, have the selected row highlighted with a black background, and change text-color of that row specifically to white, so it is readable in the contrast-color environment/theme

### Your environment 🌎

<details>
Mainly using Firefox Browser, but info is below.

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
  npmPackages:
    @emotion/react: ^11.5.0 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/styles: ^4.11.4 => 4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.33
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.3 => 4.4.4

</details>

**Comment by DanailH** [comment]
Hi, @VladParshin thanks for raising this.

Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

That being said some of the grid components have a higher specificity. This is due to performance implications. You can find more about it here: https://mui.com/blog/mui-x-v5/#simplified-style-customization.
The row and cell components are one of those, so in order to overwrite them, you would need to do it using the class name and do it through the root.

**Comment by oliviertassinari** [comment]
@VladParshin Based on the code example and the npm versions shared, I conclude that this is about v4. The code snippet is not working because the class name path used is not correct. Refer to the source on how the styles are applied

https://github.com/mui-org/material-ui-x/blob/af50a4a9974f14afc09ce7639da4f326909c7270/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts#L218-L228

In v5, we now have a `row` slot that could make it a bit simpler. I guess this issue reinforces how we could improve the docs on style customization, and maybe #2685.
