### ISSUE TITLE
Facing issue in  implement Multiple CheckBox in DatagridPro. 

### ISSUE THREAD

**Issue by wahajStar** [mui-org/material-ui-x#3327]
I am using DatagridPro with multiple checkbox.
on Changing the cell checkbox state, the header checkBox is not changed.

In the below example, You will get the data on click of "getData" button and after fatching data in datagrid .

Click the "AfterDataChange" Button and see the console for the grid changes.

Please advice, if there any optimise solution for this.

https://codesandbox.io/s/kind-bassi-3431z?file=/src/App.js:261-285

**Comment by flaviendelangle** [comment]
It is a React misusage on your side.

In the `renderHeader` you are accessing your `rowData` variable, but since you are in a `useState`, the columns object you created has not been re-created after the data object, so your `rowData` variable is the old one.
You can check it by doing a `console.log(rowData)` in your `renderHeader`.
The method is called when loading the new data, but with only access to the old `rowData`.

We strongly advise you against accessing your rows like that because you would have the columns depending on the rows and the Grid would have to re-render everything anytime a row changes.

Instead, you can access the rows from our state with the `useGridApiRef`. 
Here is an updated example: https://codesandbox.io/s/lucid-gwen-qjk12?file=/src/App.js


Anothing thing, you are mutating the data in `handleToggleSingle`, I can't say if it will cause an actual bug, but it is something you should never do in a React component.
Because lots of components rely on the object reference to apply update behavior. If you mutate the object, you change it's value but not it's reference, so update behavior may not apply.
And you are calling `setData` inside `setData` instead of returning the value.

**Comment by wahajStar** [comment]
Thank you so much for your support.

**Comment by JudeShamsi** [comment]
Is it only possible to have multiple checkboxes when you use the pro version?

**Comment by flaviendelangle** [comment]
What do you mean by multiple checkboxes ?

**Comment by dharmendra-singh01** [comment]
are multiple checkbox columns are supported in pro version only?

**Comment by flaviendelangle** [comment]
We don't support multi checkbox columns at all
But I don't understand the use case you are going for

**Comment by dharmendra-singh01** [comment]
No, let me make my question a bit clear. we have this property checkboxSelection - it adds a checkbox column, right? I want to have 3 such columns. I am facing issue to achieve the same . @flaviendelangle

**Comment by flaviendelangle** [comment]
OK
And do you want those 3 columns to have a shared state ? 
When you select a row on one column, should it check the other two ?

If so, you should be able to duplicate the checkbox column (I would have to check)
If not, then our selection plugin is not ready for this use case at all. Our model is a list of selected rows, we can't store several selection information per row for now.

**Comment by wahajStar** [comment]
@dharmendra-singh01  U can provide a small  sandbox example with your use case ....so may be its easy to fix your problem......
