### ISSUE TITLE
[DataGrid] Can't go to next page after changing `pageSize`

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#3328]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have a DataGrid with 100 rows. Initially, `pageSize` is 100, so there's only one page. If I change this prop to a lower value, e.g. 50, which would display two pages, the button to go to the next page doesn't work.

### Expected behavior 🤔

It should allow to change the current page.

### Steps to reproduce 🕹

Steps:

1. Open https://mui.com/components/data-grid/demo/
2. Change the value in the "Page Size" combo to 25
3. Click to apply the changes
4. Click the next page button

### Context 🔦

I thought this could be something only on this demo but it happens everywhere. I tried to find the cause and I noticed that `pageSizeChange` is not being fired. In the line below, `newSubState` is already equal to the prop value so it doesn't fire the event.

https://github.com/mui-org/material-ui-x/blob/cee237389d31192aa51222555ea9a36a83ecd2dd/packages/grid/_modules_/grid/hooks/core/useGridControlState.ts#L41

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Indeed, we use this `pageSizeChange` event internally to fire the `state.pagination.page` / `state.pagination.pageCount` values refresh.

So in your example, as the event is not fired, the `pageCount` stays to 1 and thus you can't go to the 2nd page.

If we fire the event whenever the new value is different from the one in the state instead of the one of the state, people would receive the control state change event twice when updating from our UI:
- When our internal code calls `setPageSize` (or another control updater) from the UI component
- When our internal code calls `setPageSize` from the `useEffect` who syncs the props and the state
