### ISSUE TITLE
[DataGrid] Persisted checkbox focus

### ISSUE THREAD

**Issue by adelinebourgeois** [mui-org/material-ui-x#3382]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we click on a checkbox and we want to click somewhere else, DataGrid keep the focus on the checkbox and scroll back to it.

### Expected behavior 🤔

When we click on a checkbox and we want to click somewhere else, DataGrid lose the focus on the checkbox and don't scroll back to it.

### Steps to reproduce 🕹

Steps:

1. Click on the checkbox
2. Scroll the page and click somewhere else

https://user-images.githubusercontent.com/12998550/145240398-49222395-b1c3-4a6d-ae03-994428f15dc2.mov

### Context 🔦

I used the DataGrid checkbox selection in my work and need to be able to scroll at the top of the page to click on a button after I choose the checkboxes without scrolling back.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
When we click on a checkbox, the Cell looks focused (blue outline) because in has the focus within it.
But it is not focused according to the state of the Grid because we stop the event

https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx#L44

So when we click outside of the Grid, the `handleDocumentClick` consider that there is no focused cell and tries to focus the last cell we clicked on: the cell of the checkbox.


I think this `event.stopPropagation` was meant to avoid double selection when clicking the checkbox due to row click selection + checkbox change selection.

But now that we pass the `checked` / `unchecked` value to the `rowSelectionCheckboxChange` event, even with this double selection, it seems to work fine.

So I think we can just remove the `event.stopPropagation`

____

A more global solution would be to avoid this state inconsistency.

**Comment by alexfauquette** [comment]
@flaviendelangle I tested, and simply removing the `event.stopPropagation` is not possible, because it causes bugs with the multi-row selection.

Surprisingly, when selecting a range of rows, the two last rows are not selected. Bellow the why:

- The `handleRowClick` call `expandRowRangeSelection` with correct row ids
- rows are selected and the `lastRowToggled.current` is updated
- The `handleRowSelectionCheckboxChange` call the `expandRowRangeSelection` but rows are already toggle, and the  `lastRowToggled.current` is wrong. Then it will unselect the rows. The reason why it is the two last rows and not only the last one is the following condition
```js
if (startIndex > endIndex) {
  endId = visibleRowIds[endIndex + 1];
} else {
  endId = visibleRowIds[endIndex - 1];
}
```

**Comment by oliviertassinari** [comment]
> So I think we can just remove the event.stopPropagation

+1 for exploring this path deeper. From my experience so far, the number of cases where `event.stopPropagation` is the "right" solution is rare. You will find a very limited. https://css-tricks.com/dangers-stopping-event-propagation/ shares some light on why `event.stopPropagation` is problematic (also true for developers that want to customize the grid).

**Comment by adelinebourgeois** [comment]
Thank you for the fix ! 😃
