### ISSUE TITLE
[DataGridProp] GridColDef missing pinnable field

### ISSUE THREAD

**Issue by david-ic3** [mui-org/material-ui-x#3398]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are missing a pinnable flag in the column definition.

For other menu options, we have sortable , filterable , etc.

### Motivation 🔦

- for consistency
- to easily allow removing the option to pin columns from the column menu and still have a few pinned columns.

### Order ID 💳 (optional)

#19458

**Comment by david-ic3** [comment]
Hi, we are not entitle to a nice proplan label ?

**Comment by m4theushw** [comment]
Thanks for the suggestion. This is definitely something we should implement. For now, you can pass a custom menu component as explained in https://mui.com/components/data-grid/columns/#blocking-column-unpinning. Since the component receives the column, it can render the column pinning menu items depending on the field:

```tsx
<GridColumnMenuContainer
  hideMenu={hideMenu}
  currentColumn={currentColumn}
  {...other}
>
  <SortGridMenuItems onClick={hideMenu} column={currentColumn} />
  <GridFilterMenuItem onClick={hideMenu} column={currentColumn} />
  <HideGridColMenuItem onClick={hideMenu} column={currentColumn} />
  <GridColumnsMenuItem onClick={hideMenu} column={currentColumn} />
  {currentColumn.field !== "email" && (
    <GridColumnPinningMenuItems onClick={hideMenu} column={currentColumn} />
  )}
</GridColumnMenuContainer>
```
