### ISSUE TITLE
[DataGrid] How to force the filter to search a hidden column

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3591]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

How to force the filter to search a hidden column.

### The problem in depth 🔍

A column that is hidden does not perform filters.

Column: "Identificação"

Prints:

![image](https://user-images.githubusercontent.com/30248434/148839792-2b8c9469-65f8-4e4f-b8f7-128e2bb7765c.png)
![image](https://user-images.githubusercontent.com/30248434/148839828-161b916e-9e6d-4f35-b33f-21df4731c281.png)

### Context 🔦

A DataGrid column called "Identificação" is hidden from the user until the user selects to display it. However, the filter only searches if the column is enabled and visible. Is it possible to force the filter to search for any column, whether it is visible or not?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
I'm not sure if I understood the problem here. If I try to filter on a hidden column in https://mui.com/components/data-grid/demo/ it works.

<img width="500" src="https://user-images.githubusercontent.com/42154031/148855483-20201fb3-a7fd-4a9c-9cc1-cc63ed46b92c.gif" alt="msedge_fiQM0SmDof" style="max-width: 100%;">

If you could describe a bit more the problem and how you're filtering it would be better, or provide a live example. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.

**Comment by lincolnmqs** [comment]
@m4theushw I didn't notice it wasn't filtering, thanks!

**Comment by m4theushw** [comment]
> I didn't notice it wasn't filtering, thanks!

Sorry, but is it working correctly for you? May I close this issue?
