### ISSUE TITLE
[DataGridPro] can't select header on double click

### ISSUE THREAD

**Issue by wahajStar** [mui-org/material-ui-x#3592]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am trying to select column header on double click  in datagridpro as default functiomality as DataGrid but its not working.
In below I attach an example.  first datagrid pro columnHeader "Group"is not selected as second Datagrid "Group" header.

[Example](https://codesandbox.io/s/distracted-resonance-6wedv?file=/src/App.js)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment]
Thanks for reporting this issue.

It seems the draggable layer is capturing the events from its children elements, which makes it impossible to select the text inside the header.

**Comment by m4theushw** [comment]
It works in the DataGrid because it doesn't have support for column reorder. To allow the column headers to be draggable, we set the `draggable` attribute to `true` which makes the browser to add a default CSS rule to block text selection. This was also pointed in https://stackoverflow.com/a/51217152.

![image](https://user-images.githubusercontent.com/42154031/149159331-39e1437c-c749-4d98-9f89-79335d2844b1.png)

There's a quick fix which is to change the `userSelect` back to `auto`. Does it solve your case?

```tsx
<DataGridPro
  sx={{
    "& .MuiDataGrid-columnHeaderDraggableContainer": {
      userSelect: "auto"
    }
  }}
/>
```

**Comment by wahajStar** [comment]
thanks for your support.
now its working exacatly as i want.
