### ISSUE TITLE
[DataGridPro] What is the configuration to export all table rows?

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3610]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

There is csvOptions configuration to export all columns "allColumns". Is there for the lines too? I'm using the "Group and Pivot" functionality, and my extended lines only export if they are opened.

### The problem in depth 🔍

In the image I highlighted the lines that are being exported, but the last one is the same as the second and is not being exported because it is not open.

![image](https://user-images.githubusercontent.com/30248434/149205065-24c4d7f9-3059-4142-9f5b-1413552bebf6.png)

There is this configuration for the documentation (https://mui.com/api/data-grid/grid-csv-export-options/)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The current export logic is as follow

If there is at least one selected rows, export the selected rows.
Otherwise, export all the rows that pass the filtering process (ie:  the rows matching the `filterModel` and not collapsed)

We have another issue of someone asking to export all the rows even when some are selected.
I feel like we could add a new option to `GridCsvExportOptions`.
Something like `getRowsToExport?: (allRows: GridRowModel[]) => GridRowModel[]` which would let users pick whatever rows they want for there custom usecase.

@joserodolfofreitas @DanailH what is your feeling on this ?

**Comment by joserodolfofreitas** [comment]
I agree that a `getRowsToExport` could be useful when we think about customization. But regarding the default behavior, I'd also expect to get the data from the collapsed rows as well (if they are matching the current filtering criteria), and I'd expect that because a collapsed row has more to do with UX and better visualization, than with data operations per se (like the filtering).

**Comment by flaviendelangle** [comment]
So for you the default behavior should be : all the rows passing the filter models, including the collapsed children ?

Side note, for #3277 having a custom callback will be even more useful to allow to export only the leaves for instance.

**Comment by flaviendelangle** [comment]
I will probably take this enhancement once the #3550 and #3554 are finishes :+1:
