### ISSUE TITLE
[DataGrid] isRowSelectable returns an error when using server side selection

### ISSUE THREAD

**Issue by Ludo978** [mui-org/material-ui-x#3614]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using server side pagination and I want to keep the selection when I change the page so I did like in the documentation (https://mui.com/components/data-grid/selection/#usage-with-server-side-pagination).
But when I add the isRowSelectable attribute, it returns the error: No row with id _rowId_ found.
Example: https://codesandbox.io/s/controlledselectionserverpaginationgrid-material-demo-forked-o8s12

### Expected behavior 🤔

This function shouldn't return an error even if we have selected rows that are not displayed.

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/controlledselectionserverpaginationgrid-material-demo-forked-o8s12
2. Select rows
3. Change page

### Context 🔦

I need to keep both functionality enabled and I tryed to do it differently without success.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.6.0 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.60
    @mui/icons-material: ^5.1.1 => 5.2.4
    @mui/lab: ^5.0.0-alpha.55 => 5.0.0-alpha.60
    @mui/material: ^5.1.1 => 5.2.4
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.4
    @mui/styles: ^5.1.1 => 5.2.3
    @mui/system:  5.2.4
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid: ^5.0.1 => 5.2.0
    @types/react:  17.0.37
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  4.5.4

```
</details>

**Comment by flaviendelangle** [comment]
Thanks for the bug report.
We have two components creating an object with the selected rows that can be selected (ie: for which `isRowSelectable` returns `true` if defined).

The problem is that we call `isRowSelectable` for every selected row and in your case some of the rows are not provided to the grid since you paginate on the server. So the function creating the params to pass to `isRowSelectable` crashes.

For one of the two components, we were calling it uselessly on the rows of the other pages so I just modified the behavior and it should work fine.

But for the other component, which is the checkbox in the header, we have a deeper change to make I think.
Because, when you paginate on the server, the grid can't know if the checkbox should be in an indeterminate mode or a checked mode. I feel like it is related to #1876, for which we could add a new callback that let the user decide the current "select all" status.

**Comment by gusbdev** [comment]
The fix will be available for V4?

**Comment by flaviendelangle** [comment]
What prevents you from migrating X to v5 ? (see [this page](https://mui.com/components/data-grid/migration-v4/) if migrating the Core to v5 is to heavy for you).

**Comment by gusbdev** [comment]
We will be migrating to v5 soon. For now I will only use the v5 data-grid. Thanks for your time
