### ISSUE TITLE
Facing issue in implementing toggleable checkbox in datagridPro

### ISSUE THREAD

**Issue by wahajStar** [mui-org/material-ui-x#3622]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We have two issues in the below example:
1) On the initial screen, the Header checkbox are selected, It should be deselected. We are setting it to False but not working as expected. 
2)  After fetching data, the Header checkbox is not working on the click. If we click on the Cell checkbox then only it works.
If you select the header you will notice nothing happen but when we select the Cell checkbox on the same column then it shows the all selected checkbox.
[example](https://codesandbox.io/s/black-dust-bpihj?file=/src/App.js)
I dont khow how to achieve this switching checkbox functionality... 

### Context 🔦

I am trying to achive switching checkbox functionality like only one option are selected "None","Read","Update",
if header checkbox is clicked it check the associate rows.

please help.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by wahajStar** [comment]
Thanks for the suggestions 
I update the code for second point its working now But I am facing issue that row requence are change when I click to single change.

step to reproduce...
after  getting data click on "None"header checkbox then click on manager "update"checkbox it will come to first row.
[https://codesandbox.io/s/ecstatic-babycat-i1ph7?file=/src/App.js](example)

**Comment by alexfauquette** [comment]
Congrats for solving your bug

Your problem is not a bug, it is a feature.

When you click on the checkbox, the click event bubbles up to the column header. And when the column header gets a click event, it starts sorting according to this column. That's why rows move when you click them.

Two possibilities:
- If you want to keep the column sorting: In the `onClick` of your header checkbox you use `event.stopPropagation()`
- You [disable the sorting on this column](https://mui.com/components/data-grid/sorting/#disable-sorting) (probably the best for your case)

**Comment by wahajStar** [comment]
Thanks  for your time...  "sortable: false," works for me.
