### ISSUE TITLE
[Docs] Country sorting doesn't work on demo page

### ISSUE THREAD

**Issue by cherniavskii** [mui-org/material-ui-x#3681]
I've noticed that country sorting doesn't work in this demo https://mui.com/components/data-grid/demo/

https://user-images.githubusercontent.com/13808724/150376741-1357d17b-b21e-4cca-bdd3-dfc88538c900.mov

I can reproduce it in storybook as well.

It seemed like an easy fix at first - just a matter of adding `valueGetter`, so that column gets sorted by country label.
It didn't work though.
Adding `valueGetter` broke `renderCell`, since `renderCell` now receives a string (returned by `valueGetter`) instead of whole field object.
I did not expect that and at this point I'm not sure if that's intended.

_Originally posted by @cherniavskii in https://github.com/mui-org/material-ui-x/pull/3564#discussion_r788924536_

**Comment by alexfauquette** [comment]
If we do encounter this problem in our demo, users probably encounter the same. It could be interesting to add in the section about [single select columns](https://mui.com/components/data-grid/columns/#special-properties) a link to the new [custom filter](https://deploy-preview-3564--material-ui-x.netlify.app/components/data-grid/sorting/#custom-comparator). Explaining that if they use a nested object, the filtering would need to be customized

Instead of fixing the demo I'm wondering if we should not change `GRID_SINGLE_SELECT_COL_DEF` such that if the value is an object it sort them according to the `value` property of this object

**Comment by cherniavskii** [comment]
> Explaining that if they use a nested object, the filtering would need to be customized

Interesting. The first thing I thought of was `valueGetter`. It's mentioned in docs, that:

> The value generated is used for filtering, sorting, rendering, etc. unless overridden by a more specific configuration.
https://mui.com/components/data-grid/columns/#value-getter

So I though, that it will cover everything. But it turned out it broke renderCell for both view and edit components.

> Instead of fixing the demo I'm wondering if we should not change GRID_SINGLE_SELECT_COL_DEF such that if the value is an object it sort them according to the value property of this object

It will only cover some cases. It won't event work for country column, since the field is called `label`.


BTW, I've noticed that filtering is also broken for that column.
