### ISSUE TITLE
Theme localization for DataGrid doesn't apply with custom translations

### ISSUE THREAD

**Issue by kasperfilstrup** [mui-org/material-ui-x#3796]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The language doesn't apply when passing in translations for DataGridPro to our custom theme. However, passing the custom translation directly to DataGridPro using `localeText` **does** apply.

### Expected behavior 🤔

I would assume that the themed localization would apply globally to all instances of DataGridPro, so that we didn't have to pass the custom translations around to each and every implementation of DataGridPro.

### Steps to reproduce 🕹

Steps:

1. Import daDK from locales
2. Create custom translation (for your language which DataGridPro doesn't support out of the box)
3. Create a theme, appending the danish locale and the custom translation to the end of the `createTheme({}, danish, customGridLocale)`
4. Wrap DataGridPro in your themeprovider, providing your theme with translations.

[Codesandbox example](https://codesandbox.io/s/datagridpro-v5-theme-localization-doesnt-apply-evs0o)

### Context 🔦

I'm trying to translate DataGridPro.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#34405

**Comment by alexfauquette** [comment]
That is because translation must indicate in which MUI component they behave. See for example how local file works for daDK in core.
https://github.com/mui-org/material-ui/blob/d3c609ba4e14cd6c1c553fb9454f72fe576649f7/packages/mui-material/src/locale/index.ts#L616

For now, X-team has only one component, the DataGrid. So we use a helper method `getGridLocalization`
https://github.com/mui-org/material-ui-x/blob/70a372129854b609a1b352167e40ac01c45fdd6c/packages/grid/_modules_/grid/utils/getGridLocalization.ts#L13

You can copy it to make your code works as follow:
https://codesandbox.io/s/datagridpro-v5-theme-localization-doesnt-apply-forked-0i199?file=/src/App.tsx

It is also possible to add your translations to the project

**Comment by kasperfilstrup** [comment]
Thank you very much Alexandre! 🙏

You're welcome to use my translations for Danish if you want to. If you need me to manually add them as a contribution, please tell me how to approach this. 🙂

**Comment by alexfauquette** [comment]
Thanks for the translation. I made the PR #3800 next release should contain Danish locale :)
