### ISSUE TITLE
[DataGrid] onRowClick is also triggered when selecting a checkbox

### ISSUE THREAD

**Issue by ak-mid** [mui-org/material-ui-x#3805]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After updating to 5.4.0 I noticed that selecting a row checkbox also triggers the onRowClick callback.
Previously that wasn't the case and I couldn't find a workaround yet to avoid that.

In my situation that new behavior breaks the logic of our product because on a onRowClick call I redirect the user to a detail page of the grid entry and on checkbox selection the user can perform actions on one or several selected entries. For now I did revert back to 5.3.0 to fix it.

### Expected behavior 🤔

On checkbox selection the onRowClick callback shouldn't be triggered like it was before 5.4.0.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

35878

**Comment by m4theushw** [comment]
This was caused because in #3501 we removed a call to `event.stopPropagation`. This change was done to fix another bug. #3492 also made a similar change which impacted [this user](https://github.com/mui-org/material-ui-x/pull/2862#issuecomment-1025877020). I would say that `onRowClick` being called is expected because we do click the row when clicking the checkbox. The grid needs to know when the row/cell was clicked to correctly track the focus, so reverting the change brings another bug. Would it help you if we provided the field that was clicked in `onRowClick` so you can avoid opening the detail page?

Currently, you can already check which field was clicked by looking at the `data-field` of `event.currentTarget`.

https://github.com/mui-org/material-ui-x/blob/cbe570cad533397324d7589e6a7e584d54e5ed4d/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts#L338-L342

https://github.com/mui-org/material-ui-x/blob/cbe570cad533397324d7589e6a7e584d54e5ed4d/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts#L344-L346

**Comment by ak-mid** [comment]
> Would it help you if we provided the field that was clicked in onRowClick so you can avoid opening the detail page?

Yes, that would definitely help and would be easy to implement in my case.

An alternative would be an option to disable ```onRowClick``` for the whole checkbox column.

**Comment by m4theushw** [comment]
Why not to use `onCellClick` instead of `onRowClick`? There you have the field in the params.

**Comment by ak-mid** [comment]
I'm using a customer key as ```row.id``` (a unique database ID) which I need to build the detail view the user is redirect to. Also in other rare situations I use different row values in combination to build follow up grids.

I guess by using ```onCellClick``` I wouldn't be able to access all other row values besides the value of the current clicked cell, right?
