### ISSUE TITLE
[DataGrid] Add toolbar

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#516]
## Summary 💡

Introduce a toolbar to perform complementary actions. 

## Examples 🌈

Items the toolbar can include:

- Filtering
- Grouping
- Sorting
- Column order
- Column visibility
- Display density
- Export/import records
- Quick search
- Add new record

## Motivation 🔦

The data grid is meant to display records, many operations & manipulator can be performed on these records, a toolbar is a great place to manage it. The Material Design specification quickly [mentions it](https://material.io/components/data-tables#anatomy) but doesn't provide guidance that we can truly leverage.

We could leverage the composability of React. We could imagine introducing new components, like a `<DataGridToolar>` component that would take the `state` object in. For instance, Stripe and Gmail introduce tabs between the toolbar and the content of the grid.

## Benchmark

- https://airtable.com, active items are colored. It works great.

<img width="1044" alt="Capture d’écran 2020-10-31 à 16 25 44" src="https://user-images.githubusercontent.com/3165635/97783105-c2f75c00-1b95-11eb-9ebe-a52af14e1f88.png">

- https://ag-grid.com, side panel, the UX is horrible, to ignore.

<img width="298" alt="Capture d’écran 2020-10-31 à 16 26 30" src="https://user-images.githubusercontent.com/3165635/97783118-db677680-1b95-11eb-959b-234810f59897.png">

- https://try.firetable.io/table/mvpResources, works OK-ish

<img width="910" alt="Capture d’écran 2020-10-31 à 16 27 59" src="https://user-images.githubusercontent.com/3165635/97783155-25e8f300-1b96-11eb-8606-90d84cefd58a.png">

- https://elastic.github.io/eui/#/tabular-content/data-grid, works well

<img width="955" alt="Capture d’écran 2020-10-31 à 16 29 32" src="https://user-images.githubusercontent.com/3165635/97783172-503ab080-1b96-11eb-90bb-2b1badda52b5.png">

- https://baseweb.design/components/unstable-data-table#data-table, displaying the filters directly, doesn't scale, not so great.

<img width="626" alt="Capture d’écran 2020-10-31 à 16 37 58" src="https://user-images.githubusercontent.com/3165635/97783369-7ca2fc80-1b97-11eb-8fca-d226a5f4fb4d.png">

- https://ads.google.com/

<img width="1162" alt="Capture d’écran 2020-10-31 à 16 54 53" src="https://user-images.githubusercontent.com/3165635/97783716-d99fb200-1b99-11eb-91cc-76cbd6d4685b.png">

**Comment by DanailH** [comment]
Below is a summary of the 2 possible ways we can achieve this feature (based on how competitors do it). Let's discuss them and choose an approach of how to tackle this. My vote goes for **Approach 2**

### Approach 1

We build the toolbar as part of the `Grid` (like how the footer is built). By default we will provide a toolbar with the functionality we assume it will be useful, but if a user wants to extend or change the default toolbar they will have to create their own and provide it to the `Grid` (same as the footer). If on the other hand, they want to hide it, there will be a prop to that as well (same as the footer).

```javascript
<DataGrid
  components={{
    toolbar: CustomToolbar,
  }}
/>
```

```javascript
<DataGrid
  hideToolbar
/>
```

#### Pros

- Easy to implement
- We have control over the responsive styles
- Doesn't require additional code to have it working. Developers don't need to copy and paste additional code to enable the feature

#### Cons

- Limited extendibility - devs will not have control over the position of the toolbar
- Adding additional functionality will mean that if they want to have the functionality of the default toolbar and just add their own features on top of it they will have to custom write the default toolbar features
- The toolbar will always be included in the bundle size (there were some thoughts around whether we could lazy-load /conditionally load it so that it can be tree shaken but there may be a limitation. Still, it is worth investigating)

### Approach 2

We create a separate `Toolbar` component from the grid. We then implement the grid features as separate components in the toolbar using the grid API.

```javascript
<Provider state={GridState}>
  <Toolbar>
    <ColumnPicker />
    <DensityPicker />
    <ColumnFilter />
    ....
  </Toolbar>

  <DataGrid
    {...data}
  />
</Provider>
```

#### Pros

- Much more extendable
- The grid bundle size will not be affected
- Familiar patter for developers (Redux does the same with the store)
- Easier for developers to add custom features on top of the ones we provide out of the box
- Can be placed anywhere the developer wants (on the side, on the bottom of the grid, etc.)

#### Cons

- Harder to implement / more time consuming
- It will probably be a bit slower to implement grid functionality in the toolbar
- We won't have much control over the responsive styles
- In order for devs to use it they would need to copy and paste example code from the docs, the toolbar will not be available by default.

If I've missed something please add it. If you have another idea or suggestion add it as well so we can discuss it.

**Comment by oliviertassinari** [comment]
👍 for option 2

**Comment by dtassone** [comment]
I suggest we start with option 1 as it's the current approach of customizing components and refactoring the grid customization is outside the scope of the toolbar. We have estimated the toolbar as a simple component using the current architecture so I suggest we stick to the plan. 
Refactoring components customization will come at a later stage, I think at the moment we have other priority.
That does not mean, you can't create a very clean toolbar with buttons like
```
<Toolbar>
    <ColumnPickerButton />
    <DensityPicker />
    <FilterButton />
    ....
  </GridToolbar>
```

This way users can still reuse the buttons... and also pave the way to the second apprach

**Comment by DanailH** [comment]
No of-course, the buttons will be separated, actually, I played a bit yesterday with the idea of having a separate provider and it turns out that it may not be that difficult to achieve. We gave access to the `useApiRef()` hook so we can control the grid from the outside.
