### ISSUE TITLE
[DataGrid] Allow "select all" to only select the active page

### ISSUE THREAD

**Issue by NickLont** [mui-org/material-ui-x#605]
When Pagination is enabled in XGrid when the "Select all" checkbox is enabled, all possible options from all pages are selected. I would like the option to select only the current paginated page options (exactly like [that](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/#with-paging))
 

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

When the pagination number per page is set to 5, when the "select all" checkbox is clicked only the current 5 options should be selected and not every possible option.
## Examples 🌈

Example from the DevExtremeREACTIVE page [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/#with-paging)

## Motivation 🔦

Building an application with a table of contacts, the use cases where a bulk action would need to affect every single contact is rare, compared to selecting only the ones currently paginated.

**Comment by oliviertassinari** [comment]
@NickLont Thanks for the issue. It seems that both approaches have their use cases. From my perspective, the default should be to select only the visible rows. Most end-users will be confused otherwise.

I like how Crowdin display a message to suggest the selection of all the rows as soon as the whole page is selected:

<img width="1189" alt="Capture d’écran 2020-11-19 à 15 56 30" src="https://user-images.githubusercontent.com/3165635/99682761-e79d7000-2a7f-11eb-9d63-0fe5d051e40f.png">

Outside of DevExpress, we can also use react-table to benchmark the difference: https://react-table.tanstack.com/docs/api/useRowSelect#example. `getToggleAllPageRowsSelectedProps()` is for the current page while `getToggleAllRowsSelectedProps()` is for everything.

**Comment by oliviertassinari** [comment]
Gmail

<img width="1013" alt="Capture d’écran 2020-11-23 à 15 03 27" src="https://user-images.githubusercontent.com/3165635/99971165-1b88d600-2d9d-11eb-9671-5dbca048c54b.png">

**Comment by oliviertassinari** [comment]
For implementing the "select all" behavior when only the current page is selected, we might need #246.

**Comment by dtassone** [comment]
Benchmark for Ag grid 
it has 2 modes
https://www.ag-grid.com/react-grid/row-selection/#select-everything-or-just-filtered
