### ISSUE TITLE
Footer total rows and selected rows disappear on adding pagination.

### ISSUE THREAD

**Issue by rajanvam** [mui-org/material-ui-x#638]
Footer  text for total rows and selected rows disappear on adding pagination. And onPageSizeChange, onPageChange are still showing weird behaviour for server side pagination.

- [ √] The issue is present in the latest release.
- [ √] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.Go to  https://codesandbox.io/s/cgbej?file=/demo.js
2. Add pagination prop
3.
4.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.10 |
| React         | 16.9.0       |
| Browser       |     Chrome    |
| TypeScript    |         |
| etc.          |         |

**Comment by DanailH** [comment]
Hi @rajanvam , sorry for the late reply. This is expected behaviour - the total rows information is present in the out of the box pagination so we hide the `Total Rows` line when `pagination` is enabled. 

Regarding the `selected rows` - they are only hidden on smaller resolutions. If you enable the `pagination` and resize the window in the demo you will see the `Selected rows` line if there are any that are selected.

Let me know if this helps.

**Comment by oliviertassinari** [comment]
> `onPageSizeChange`, `onPageChange` are still showing weird behavior for server-side pagination.

@rajanvam What do you mean?
