### ISSUE TITLE
[DataGrid] Sorting order of input rows isn't respected when `sortingMode="server"`

### ISSUE THREAD

**Issue by dmitryKochergin** [mui-org/material-ui-x#792]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the rows prop is updated, the grid does not change its appearance.
It happens only if the rows contains old ids. For example, it reproduces if I make sort in rows.

## Expected Behavior 🤔

DataGrid have to react on rows prop change. Especially when it uses with sortingMode="server".

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-rows-order-forked-fqz7e?file=/src/Demo.js

Steps:

1. Click "Reorder" button
2. In console you can see current order of rows, but in grid it doesn't change

## Context 🔦

I found this bug when I tried to make client sorting without help of DataGrid (there was few reasons for it).

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.13 |
| React         | 16.13.1 |
| Browser       | Chrome |

**Comment by DanailH** [comment]
Hay @dmitryKochergin thanks for reporting this. Actually the sorting is done a but differently in the grid than expected. First thing is that you set the `sortingMode="server"` which means that any sorting on the client side will be prevented.

Second point is regarding how the actual sort works. To sort the rows of the grid you would need to provide a `sortingModel` (you can check it here [https://material-ui.com/api/data-grid/](https://material-ui.com/api/data-grid/)).

You can check how your use case can be implemented in this example -> [https://codesandbox.io/s/material-ui-issue-rows-order-forked-vcfhs?file=/src/Demo.js](https://codesandbox.io/s/material-ui-issue-rows-order-forked-vcfhs?file=/src/Demo.js)

**Comment by oliviertassinari** [comment]
@dmitryKochergin Thanks for reporting the issue.

- It's a regression from v4.0.0-alpha.9: https://codesandbox.io/s/material-ui-issue-rows-order-forked-pzszy
- It works well in v4.0.0-alpha.8: https://codesandbox.io/s/material-ui-issue-rows-order-forked-hvu2m?file=/src/Demo.js

We need to add a regression test once we fix it. The issue is similar to #753 but different. In #753, we have broken the client-side sorting, in #792 we have broken the server-side sorting.

---

> sortingMode="server" which means that any sorting on the client side will be prevented.

@DanailH `sortingMode="server"` might be confusing in the name. It's about telling the data grid to give the ownership of the sorting state of the rows to the parent, to allow the `rows` prop to control it.

> you would need to provide a sortingModel

When the sorting is set to server-side, the `sortingModel` only controls the UI of the header, it has no impact on the rows. In the future, once the data grid start to handle lazy loading, it might change a bit.

**Comment by worksofliam** [comment]
Hi @oliviertassinari. Thanks for the fix!

When can we expect this to be released? It looks like the sprint is due by the 18th.. perhaps around then?

Is there a way I can try this fix out before then?

Thanks!

**Comment by oliviertassinari** [comment]
@worksofliam We release every week, independently from when each sprint ends or starts. Also, mind that you can use a specific pull request following https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#how-can-i-use-a-change-that-wasnt-released-yet.

**Comment by worksofliam** [comment]
@oliviertassinari Appreciate ya. Thanks a ton!
